title: Gingkoleaves
remote_theme: minitoc  

collections:
  notes:
    output: true       
    permalink: /notes/:path/
  talks:
    output: true
    permalink: /talks/:path/

# 插件配置
plugins:
  - jekyll-emoji
  - jekyll-feed