title: Gingkoleaves
remote_theme: minitoc  
future: true
home_background_image: /assets/images/bg4.jpg

collections:
  notes:
    output: true       
    permalink: /notes/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Feed
feed:
  collections:
    notes:
      path: /notes/feed.xml
    talks:
      path: /talks/feed.xml

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive
    tag: archive
    year: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    year: /archives/:year/

# 插件配置
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-toc
  - jekyll-mentions # 把 @用户名 自动变成链接（类似 GitHub）。
  - jekyll-relative-links # 让站内相对链接更稳定，文件移动后不容易坏。